# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.TextField(blank=True),
        ),
    ]
