# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0004_auto_20170909_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
        migrations.AddField(
            model_name='quote',
            name='wished_by',
            field=models.ManyToManyField(related_name='wishing', to='exam2.User'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quoted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='exam2.User'),
        ),
    ]
